In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [3]:
a=np.arange(1,101)

In [4]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
b=np.arange(501,601)

In [15]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [6]:
b.shape

(100,)

In [11]:
#train_test_split(x)--takes an array and splits it into 2 arrays
train_test_split(a)
#the first array in the output will always be the train array and the second one is the test array
#before the train_test_split, the data was ordered. Now its completely random

[array([ 50,  63,   3,  70,  10,  30,  45,   9,  49,  23,  71,  72,  41,
         27,  75,  65,  86,  21,  91,  68,  67,  12,  29,  58,   7,  35,
         99,  48,   2,  61,  78,  76,  13,  60,  80,  32,  69,  51,   8,
         83,  82,  46,  28,  25,  57,  98,   1,  36,  39,  37,  66,  97,
         56,  18,  14,  89,  24,  59,  85,  26,  15,  88,  84,  16,  52,
         93, 100,  73,  43,  33,  90,  22,  55,  87,  53]),
 array([81, 47, 40, 74, 19, 96, 79, 54, 38, 17,  6, 95, 31, 44, 42, 34,  5,
         4, 11, 77, 20, 92, 62, 64, 94])]

In [12]:
a_train,a_test=train_test_split(a)

In [13]:
a_train.shape,a_test.shape
#this shows that the default split is 75-25 and both arrays are shuffled(randomness trait)

((75,), (25,))

In [14]:
#incase you want to achieve an 80-20 split then you can use this:
a_train,a_test=train_test_split(a,test_size=0.2)
#the split value will be between 0 and 1, a floatng point value
#each time you run the code the values in train and test will be different
#if you do not want the split to be different everytime then use the random_state=number parameter.
#lets say random_state=42. Then no matter how many times we run the code we will get the same data in the train and test and not shuffled data


In [15]:
a_train.shape,a_test.shape

((80,), (20,))

In [16]:
a_train,a_test

(array([ 84,   5,   3,  46,  82,  57,  39,  77,  66,  99,  50,  49,  24,
         14,  22,  45,  78,  29,  75,  96,  44,  95,  56,  58,   7,  10,
         65,  20,   9,  86,  60,  70,   2,  98,  81,  61,  68,  19,  21,
         23,  88,  25,   8,  41,  76,  26,  79,  12,  90,  52,  28,  37,
         64,  36,  69,  38,  33,  55,  62,  34,  11,  16,  83,  73,  18,
         80,  30,  63,  89,  97, 100,  13,  87,  94,  71,  54,  35,  43,
         67,  27]),
 array([93, 40,  1, 48, 15, 53,  6, 92, 32, 72, 47, 31, 59, 85, 51, 74, 42,
         4, 91, 17]))

In [ ]:
#if we dont want the split to be of random nature(which is the case in TimeSeries Analysis), then we have to mention shuffle=False. This parameter is True by default
#E.g- a_train,a_test=train_test_split(a,test_size=0.2,shuffle=False). In this case fist 80 observations will be part of training data and the next 20 will be part of testing data

In [17]:
#we can pass more than 1 arrays at the same time in train_test_split:
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.2)