In [1]:
import numpy as np

Create a 4 x 4 matrix and add values 4,5,6 above the parent diagonal.
```
array([[0 4 0 0],
       [0 0 5 0],
       [0 0 0 6],
       [0 0 0 0]])
```

In [9]:
arr1=np.zeros([4,4])
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])