In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

arr=np.array(my_list)
arr


array([1, 2, 3])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(type(my_list))

<class 'list'>


In [5]:
print(np.result_type(arr))

int32


In [6]:
arr=np.array(['hi',2,3])

In [7]:
print(np.result_type(arr))

<U2


In [8]:
print(type(arr[0]))

<class 'numpy.str_'>


In [9]:
print(type(arr[1]))

<class 'numpy.str_'>


# casting list to a matrice or a 2-D array. notice the 2 square brackets in the o/p, denoting that its a 2-D array

In [10]:
my_list=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# using numpy built in methods for array generation

In [11]:
arr=np.arange(0,11,2)
arr

array([ 0,  2,  4,  6,  8, 10])

# specific arrays

In [ ]:
# a 1-d array with all elements as 0. 4 represents the rows. IF we mention (5,4) then 5=rows and 4-columns. notice that it has been passsed
# as a tuple-np.zeros((5,4)). notice the bracket surrounding 5,4. if bracket not there then error

In [12]:
np.zeros(4)

array([0., 0., 0., 0.])

In [13]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# linspace(start,stop,number of equally spaced elements). arange(start,stop,stepsize). linspace includes the stop value, whereas arange excludes it

In [16]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# identity matrix. no of rows=no of columns. a 2-d sqaure matrix

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# generating arrays having random elements

In [ ]:
#rand--creates an array having random samples from an uniform distribution between 0 and 1. every time you execute the set of generated values will be different
#rand(x)--for a 1-d array
#rand(x,y)--for a 2-d matrix

In [23]:
np.random.rand(4)

array([0.22812416, 0.9197468 , 0.79068001, 0.2445017 ])

In [22]:
np.random.rand(5,5)

array([[0.79284357, 0.07201053, 0.20170757, 0.25867197, 0.37965859],
       [0.849689  , 0.09244981, 0.23654493, 0.85561323, 0.9635365 ],
       [0.46216839, 0.88466975, 0.27424287, 0.59704937, 0.52501322],
       [0.15559885, 0.89506988, 0.21509586, 0.52690894, 0.03070757],
       [0.60616603, 0.03104488, 0.20795924, 0.24935475, 0.06963147]])

In [ ]:
#to return a sample from a random normal or gaussian distribution centred around 0, use randn(). Once againg the set of values will be different every time you execute
#randn(x,y)--for a 2-d array where x and y denote rows and column numbers

In [27]:
np.random.randn(2)

array([ 0.05666387, -0.99029975])

In [28]:
np.random.randn(5,5)

array([[-1.0977877 , -1.17657962, -0.44800325,  1.17272915, -0.50283695],
       [ 0.40967551, -0.86882947, -0.9218043 ,  0.25116024,  0.68547207],
       [ 0.99632321, -0.12305868, -0.40627551, -0.24381223, -0.9121518 ],
       [ 0.55674432, -1.45533802, -1.46055481,  0.6791162 ,  2.64086303],
       [ 2.12050613, -0.40861817, -0.45826824,  0.34437825,  0.52334533]])

In [ ]:
#np.random.randint(1,100)--generates a number bertween 1 and 100, including 1 and excluding 100
#randint(1,100,10)--means 10 random number between 1 and 100, including 1 and excluding 100

In [31]:
np.random.randint(1,100)

19

In [32]:
np.random.randint(1,100,20)

array([31, 82,  9, 42, 10, 37, 46, 38, 19, 72, 97, 49, 93, 58, 82, 25, 45,
       30, 86, 67])

In [ ]:
#methods to use on arrays
#generate 2 sample arrays arr and rarr

In [33]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
rarr=np.random.randint(0,50,10)
rarr

array([33, 12, 12, 19, 16, 20, 41, 42, 18, 20])

In [ ]:
#use reshape()-returns the same data but different dimension. rows*columns=number of elements. So arr is having 25 elements, which means while reshaping it we can have only 5*5
#reshaped to 2-d array
#rarr can be reshaped to 2,5 or 5,2 as there are total 10 elements

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
rarr.reshape(2,5)

array([[33, 12, 12, 19, 16],
       [20, 41, 42, 18, 20]])

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
rarr.reshape()

array([33, 12, 12, 19, 16, 20, 41, 42, 18, 20])

In [40]:
rarr.max()

42

In [41]:
rarr.min()

12

In [ ]:
#to find the location or the index value of the max or min element use argmax or argmin.
#notice that the index returned is 4 and it is as per the original rarr 1-d array before reshaping. inthat 48 is placed at index location 4. scroll up to see. also
# see how reshaped values are appearing

In [42]:
rarr.argmax()

7

In [43]:
randarr=np.arange(0,10,1)

In [44]:
randarr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
randarr.shape

(10,)

In [46]:
newarr=randarr.reshape(2,5)
newarr.shape

(2, 5)

In [47]:
newarr.dtype

dtype('int32')

# Numpy Indexing and selection

In [60]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

In [ ]:
arr[1:4]

In [ ]:
arr[:-1]

In [ ]:
arr[:]

In [ ]:
#broadcasting a value to some specific elements. select the elements using slicing and make that = value

In [61]:
arr[1:5]=100
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
arr[1:5]=[1,2,3,4]

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
newarr=arr
newarr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
newarr[1:4]=[1,2,3]
newarr

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [65]:
arr

array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr_copy=arr.copy()

In [55]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr_copy[:5]=100

In [58]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#indexing 2-d array or matrix

In [66]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [71]:
arr_2d[:][2]

array([35, 40, 45])

In [69]:
arr_2d[1][2]

30

In [ ]:
#you can get the same result as above with single bracket notation-- arr_2d[1,2]

In [72]:
arr_2d[1,2]

30

In [73]:
#to capture part of array
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d[0:2,0:2]

array([[ 5, 10],
       [20, 25]])

In [75]:
arr_2d[1:2,1:2]

array([[25]])

In [76]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#conditional selection

In [77]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
bool_arr=arr>5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [82]:
arr%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [83]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [84]:
arr_2d=np.arange(50).reshape(5,10)

In [85]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [86]:
arr_2d[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [ ]:
#array operations. element wise operations

In [87]:
arr=np.arange(0,11)

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [90]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
#add,subtract,multiply a number to each element of the array

In [91]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [92]:
#1/0 gives you an array. however numpy will jsut issue a warning

In [93]:
arr/0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [94]:
arr/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
arr**2

In [ ]:
#universal array functions.perform operatrions and brodcast across the entire element set of the array. check the numpy docs for universal functions-ufunc

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [ ]:
np.logical_and(arr,arr)

In [95]:
np.fmax(arr,arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1=np.arange(1,12)

In [ ]:
np.fmax(arr,arr1)

In [ ]:
np.reciprocal(arr)